### ISSUE TITLE
What it's status now?

### ISSUE THREAD

**Issue by nvcken** [luxeengine/support#26]

**Comment by AlexanderEvans** [comment]
Hey, umm... I am also curious, is this project still alive?  Was really hoping to see what the 1.0 build looked like and being able to play with it, but I haven't seen any updates or heard anything for quite a while, even though "this is going to be a *great* year for lux" so I was just kinda wondering if this was still being developed, or....what?  Did some kind of delay come up?  If so that's fine, but can you please post an update or something and let us know?  I'm just hoping this project hasn't been abandoned...

**Comment by AlexanderEvans** [comment]
Ok, thanks, I had checked the twitter but the last tweet from the official twitter was back from august and I hadn't seen anything on the @___discovery account relevant since late September.  But as long as the project is still alive, that's great, take your time, and I'll be looking forward to it.  😄

**Comment by underscorediscovery** [comment]
Yea, I know that the lack of posts isn't ideal, I recently moved across the country, work that I need to do and have other things going on, it is what it is :D 

Still, I have a post close to done that I'll get up soon. 

Thanks for checking in though!
