### ISSUE TITLE
How to create a spotlight effect?

### ISSUE THREAD

**Issue by hexdie** [luxeengine/support#4]
Hello, in the game I'm working on, I wanted to create a spotlight effect where the player has an area of visibility in an otherwise dark room. I implemented a naive approach by creating an animated texture and placed it over the entire screen. Here's what that looks like:

![gf2](https://cloud.githubusercontent.com/assets/9022850/18145305/354b93d6-6f90-11e6-8fb2-91624ee25bdf.gif)

What I'd like to be able to do is make it pretty much this but with the ability to place these "spotlights" over enemies and other entities (like torches). So in the gif above, after the first enemy died, the room would get darker and spotlights would appear, but the remaining enemy would have a spotlight around it as well.

I realize this texture-based approach isn't going to work for this but I'm not sure what I'd do otherwise to create this effect. Any help would be appreciated. Thanks!

**Comment by underscorediscovery** [comment]
You have two options that amount to what you can view as _compositing_.

Imagine an image editor, how would you apply the effect?

- make a layer with the circles in it 
- put it above the other layers

This is quite straight forward, but if you haven't done this type of stuff before it can feel a bit alien. Just keep in mind that you're drawing in layers, and the layers contents are in luxe, at the moment, driven by the batcher notion.

So, there are a few ways to achieve this. I'll suggest two more straight forward ones.

**option 1: blend modes**

1. Put your lights/circles _as geometry_ (or textured geometry) into a batcher. Set the layer of the batcher above the default one - so it's drawn on top. There are a few places with examples of the batchers, let me know if you need links.

2. Set the rendering blend mode for that batcher, before it renders you set it to a "additive" or subtractive, or whichever blend mode. Then when it's done that layer, reset it. This is explained [here in the render control guide](https://luxeengine.com/guide/#rendercontrol). It's also demonstrated in the [tests/rendering/groups_and_blendmodes](https://github.com/underscorediscovery/luxe/tree/master/tests/rendering/groups_and_blendmodes) example code as a starting point. [This tool](http://www.andersriggelsen.dk/glblendfunc.php) has a easy way to preview the blend modes and is linked there too.

This is quite simple, and the key to consider for compositing is the _destination_. Where are you rendering to - that determines what the contents you are drawing will be blended against. If that's "the existing frame till now" then in the above it's really simple. Just do those two things and you're done.

**option 2: render to a texture**

This approach will also probably lead to blending (either in a shader, or using the hardware blend modes). 

The basic idea is similiar, but your _destination_ changes. Instead of rendering over "the existing frame till now" you render to a texture that you first create for that purpose. You can draw all lights into the one texture, using a batcher, and then you can use that texture however you want. This let's you put the texture onto a sprite, and display it on top - which can use hardware blend modes, or can apply a shader, or can just be drawing using alpha of the geometry. This would be how you combine multiple lights into one surface that you draw on top. 

Since the texture can be cleared to no color, no alpha, you can "cut out" stuff by rendering into it. Clear it black, draw a circle geometry with full alpha, you now have a whole cut out from the texture. You can do this with multiple lights, if that makes sense?

---

Hopefully that's enough to get started. If you have more specific questions let me know.

**Comment by hexdie** [comment]
Option 1 seems to be what I need. I was thinking something with blend modes was an answer, but I wasn't sure of how to go about it. What you've said here makes sense though, so I'll give that a try. Thanks again for your awesome help!

**Comment by hexdie** [comment]
So I've taken a crack at this, but it's not there yet. Here's a screenshot of what I have so far:

![spotlight-blend](https://cloud.githubusercontent.com/assets/9022850/18152108/18fcf4ee-6fb9-11e6-9fd6-d6684d5b9048.png)

It's doing some of what I'd like it to do. The coloring of the texture shows the image below, while the alpha portion of the texture is blacked out. But, it appears the blacked out portions of those textures show through each other. Also, the black doesn't extend out past the texture ,which makes sense. Any idea how I'd go about resolving those issues?

For reference:

The lights are created using this texture (it's animated, so four frames):

![spotlight-effect](https://cloud.githubusercontent.com/assets/9022850/18152121/2c5f7c46-6fb9-11e6-8724-f8fb3568453f.png) 

Here's the code I have for creating the batcher:
```
batcher = Luxe.renderer.create_batcher({
	name: "light-batcher",
	camera: Luxe.camera.view,
	layer: 2
});

var texture:Texture = Luxe.resources.texture("assets/images/darkness.png");
texture.filter_mag = texture.filter_min = FilterType.nearest;

batcher.on(prerender, onPrerender);
batcher.on(postrender, onPostRender);

private static function onPrerender(b:Batcher)
{
	Luxe.renderer.blend_mode(BlendMode.zero, BlendMode.src_alpha);
}

private static function onPostRender(b:Batcher)
{
	Luxe.renderer.blend_equation();
	Luxe.renderer.blend_mode();
}
```

All of the sprites of the lights are being added to this batcher by passing the batcher in with the SpriteOptions used to create those sprites. Thanks again!
`

**Comment by hexdie** [comment]
I tried again and I got it working! I took the second option you suggested, which was to render a texture.  The method I used is encapsulated here: https://bitbucket.org/snippets/hexdie/eokdz

And here's what it looks like:

![glow-flower-room-lighting-2](https://cloud.githubusercontent.com/assets/9022850/18187933/599991c8-7073-11e6-9a46-d479c69b9775.gif)

The only issue I'm having now is that when I resize the window, the display sprite doesn't seem to stay in position. If I increase the size of the window a bit, while staying the same position I was in for that last gif, it looks like this:

![gflight-issue](https://cloud.githubusercontent.com/assets/9022850/18188008/ede4361c-7073-11e6-81af-6a85bb0b5d53.png)

And it just moves more and more down and to the right as the window size increases. It's probably some mistake I'm making though, so I'll look into it. Thank you for your help, @underscorediscovery !

**Comment by hexdie** [comment]
Sorry to bother you again @underscorediscovery but I'm not really sure what's going on. It seems the position of the "cutouts" or spotlights are changing based on the window size. Here's the behavior I'm seeing:

![glow-flower-room-lighting-issue-resize](https://cloud.githubusercontent.com/assets/9022850/18189405/3bcaccc2-7080-11e6-9fe0-5cc8ea58abed.gif)

Would you happen to know of any reasons why this might be occurring? I'm pretty stumped.

**Comment by underscorediscovery** [comment]
Well, keep in mind that the texture you created (the render texture, i.e the destination) is typically in your case created to match the window size. 

If the window size changes, you must destroy the target, and create a new one of the right size. Also your display sprite for it, make sure centered is false, and leave it's position at `0,0`.

**Comment by hexdie** [comment]
Thanks @underscorediscovery ! That helped quite a bit. I also realized part of my issue was not clearing the camera before the batcher I set up for this rendered. 

I still have one issue, which is that the sprites I'm rendering to the target is still being offset when the window is resized. It snaps back nicely after viewport sizes up to the next size (I'm using [this code](https://github.com/MicUurloon/LuxePixelPerfect) to handle the viewport resizing) but every window size inbetween seems to offset the part I want. Here's what that looks like:

![glow-flower-room-lighting-issue-resize-3](https://cloud.githubusercontent.com/assets/9022850/18191398/89a30d6a-708f-11e6-8eb7-593b063122bf.gif)

The red in that image is the clear color I'm setting, so I believe the display sprite is always staying the same position, but the actual sprites I'm rendering to it are still offsetting. Would I have to translate the coordinates I have for those sprites from world coordinates to something else? Or is there something else I might be missing? Thanks again so much for helping me out!

**Comment by underscorediscovery** [comment]
It's quite hard to tell what's going on. I'd suggest starting simple, take one step at a time, and eliminate assumptions. What causes a sprite position to be where it is on screen? position, origin, the camera position, the camera viewport, and in this case, the sprite that's displaying it, and the texture that it's being displayed in.

You have some coordinate systems that have to speak the same language, they have to agree on what's happening. When one of them doesn't, you get this type of confusion. I'd disable them one at a time and find which one is confused. 

What i'd suggest is, leave the window alone, and call the resize function manually, with a smaller value, i.e set the size explicitly. The size you pick should be predictable, so the values you're _expecting_ are a known value, a ground truth. Then check where it's falling over. 

My guess is that the batcher that draws into the texture, it's view isn't right.
Also keep in mind "window size" in my above message, meant the size you're displaying the texture at and not the literal size - i.e it must match the border of the game and not the window if you're adding letter/pillarboxes.

It's near impossible to give any more help without seeing the code itself, but I think it's better to understand what's going on. 

One step at a time, use known/expected quantities, and explicitly invoke the chain of events that updates it.

**Comment by hexdie** [comment]
I'll give that a try and figure this out. I'll close this issue now because the initial issue has been solved. Thanks a bunch @underscorediscovery !
